# Para recuperar informacion
GET http://localhost:1234/pokemon/ditto


# Para crear un pokemon

// Probando con Thunder Client poner en modo POST y pasarle el JSON

POST http://localhost:1234/pokemon 
Content-Type: application/json
{
    "name": "ditto",
    "type": "normal",
    "level": 1
} 